version: '3.8'

services:
  postgres:
    image: postgres:latest
      # Host name / address
    container_name: postgres
    environment:
      # Maintenance database
      POSTGRES_DB: taskManagement 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: